(define (reverseDup l)
  (let ((rev (reverse l)))
     (append rev rev)
  )
)

(define (binpow a b)
  (if (zero? b) 1
    (let ((bp (binpow a (div b 2))) (rem (remainder b 2)))
      (if (zero? rem)
        (* bp bp)
        (* a bp bp)
      )
    )
  )
)

;if (b % 2 == 0) -> binPow(a, b/2) * binPow(a, b/2)
;else -> a * binPow(a, b/2) * binPow(a, b/2)

(define (fib-helper a b n)
  (if (zero? n) a
    (fib-helper b (+ a b) (- n 1))
  )
)

(define (fib_ n)
  (fib-helper 0 1 n)
)

(define (fib n)
  (let fib-rec ((a 0) (b 1) (i n))
    (if (zero? i) a
      (fib-rec b (+ a b) (- i 1))
    )
  )
)

(define (partition n l)
  (if (null? l) '(()())
        (let ((part (partition n (cdr l))))
          (if (< (car l) n) (list (cons (car l) (car part)) (cadr part))
            (list (car part) (cons (car l) (cadr part)))
          )
        )
  )
)

(define (count l e)
  (apply + (map (lambda (x) (if (= x e) 1 0)) l))
)

(define (permutation? l1 l2)
  (if (= (length l1) (length l2))
    (= 0 (apply + (map (lambda (e) (if (= (count l1 e) (count l2 e)) 0 1)) l1))) 
    #f
  )
)

(define (is-way-helper l visited a b)
  (cond ((= a b) 1)
        (else (apply + (map (lambda (e) 
                      (cond ((and (= (car e) a) (= 0 (count visited (cadr e)))) 
                              (is-way-helper l (cons (cadr e) visited) (cadr e) b)
                            )
                            ((and (= (cadr e) a) (= 0 (count visited (car e))))
                              (is-way-helper l (cons (car e) visited) (car e) b)
                            )
                            (else 0)
                      )
                   )
               l)
            )
        )
  )
)

(define (isWay? l a b)
  (> (is-way-helper l '() a b) 0)
)
